### ISSUE TITLE
Error importing csv files with Neo4j v.5.21.2

### ISSUE THREAD

**Issue by mbaric758** [biocypher/biocypher#363]
Problem with importing data with version 5.21.2. The problem seems to occur whenever trying to define a database to import to at the end of the import sequence, for example the name is neo4j here below. Even if the database exists (for example using the name of the default database), there's a `File 'neo4j' doesn't exist` error. Everything works correctly if the name of the database is deleted altogether, the import is then correct, and imports to the default database (neo4j).

In addition to that, in previous versions of Neo4j changing the` initial.dbms.default_database= `name in ` neo4j.conf ` was enough to change the default database and import there by changing the database name at the end of the import sequence, but here it seems to be creating problems with the new version.

For example:

`
neo4j-admin database import full --delimiter=";" --array-delimiter="|" --quote="'" --overwrite-destination=true --skip-bad-relationships=true --skip-duplicate-nodes=true --nodes="/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/Patient-header.csv,/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/Patient-part.*" --nodes="/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/SequenceVariant-header.csv,/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/SequenceVariant-part.*" --relationships="/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/PatientHasVariant-header.csv,/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/PatientHasVariant-part.*" neo4j --verbose`

And this is what I get with --verbose:

```
Executing command line: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java -cp /Users/mbaric/neo4j-community-5.21.2/plugins/*:/Users/mbaric/neo4j-community-5.21.2/conf/*:/Users/mbaric/neo4j-community-5.21.2/lib/* -XX:+UseParallelGC -XX:-OmitStackTraceInFastThrow -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -Djdk.nio.maxCachedBufferSize=1024 -Dio.netty.tryReflectionSetAccessible=true -XX:+ExitOnOutOfMemoryError -Djdk.tls.ephemeralDHKeySize=2048 -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED -Dlog4j2.disable.jmx=true -Dfile.encoding=UTF-8 org.neo4j.cli.AdminTool database import full --delimiter=; --array-delimiter=| --quote=' --overwrite-destination=true --skip-bad-relationships=true --skip-duplicate-nodes=true --nodes=/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/Patient-header.csv,/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/Patient-part.* --nodes=/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/SequenceVariant-header.csv,/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/SequenceVariant-part.* --relationships=/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/PatientHasVariant-header.csv,/Users/mbaric/ontoweaver1/biocypher-out/20240716155548/PatientHasVariant-part.* neo4j --verbose
neo4j 5.21.2
VM Name: Java HotSpot(TM) 64-Bit Server VM
VM Vendor: Oracle Corporation
VM Version: 17.0.10+11-LTS-240
JIT compiler: HotSpot 64-Bit Tiered Compilers
VM Arguments: [-XX:+UseParallelGC, -XX:-OmitStackTraceInFastThrow, -XX:+UnlockExperimentalVMOptions, -XX:+TrustFinalNonStaticFields, -XX:+DisableExplicitGC, -Djdk.nio.maxCachedBufferSize=1024, -Dio.netty.tryReflectionSetAccessible=true, -XX:+ExitOnOutOfMemoryError, -Djdk.tls.ephemeralDHKeySize=2048, -XX:FlightRecorderOptions=stackdepth=256, -XX:+UnlockDiagnosticVMOptions, -XX:+DebugNonSafepoints, --add-opens=java.base/java.nio=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, -Dlog4j2.disable.jmx=true, -Dfile.encoding=UTF-8]
Configuration files used (ordered by priority):
/Users/mbaric/neo4j-community-5.21.2/conf/neo4j-admin.conf
/Users/mbaric/neo4j-community-5.21.2/conf/neo4j.conf
--------------------
java.lang.IllegalArgumentException: File 'neo4j' doesn't exist
        at org.neo4j.kernel.impl.util.Validators.matchingFiles(Validators.java:52)
        at org.neo4j.kernel.impl.util.Converters.lambda$regexFiles$2(Converters.java:49)
        at org.neo4j.kernel.impl.util.Converters.lambda$toFiles$3(Converters.java:65)
        at org.neo4j.importer.ImportCommand.parseFilesList(ImportCommand.java:725)
        at org.neo4j.importer.ImportCommand$InputFilesGroup.toPaths(ImportCommand.java:692)
        at org.neo4j.importer.ImportCommand$Base.doExecute(ImportCommand.java:451)
        at org.neo4j.importer.ImportCommand$Full.execute(ImportCommand.java:611)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
        at org.neo4j.cli.AdminTool.main(AdminTool.java:82)

```

The files are imported correctly to the default database (neo4j), if I don't add a database name at the end of the import sequence, and if I don't modify the initial.dbms.default_database= line in neo4j.conf.

**Comment by slobentanzer** [comment]
@mbaric758 Thanks for reporting! @nilskre do you have time to check?

@mbaric758 What/where exactly seems to be the underlying issue?

**Comment by mbaric758** [comment]
Hi @slobentanzer , it seems like the issue was with the placement of the database name in the import call. It should be placed directly after the import prefix. I did a PR to fix the issue.
